### ISSUE TITLE
İngilizce/Türkçe Dil Manuel Değiştirme

### ISSUE THREAD

**Issue by tarikccn** [recepbasturk/clock_game#1]
Merhaba;
Uygulamanızda Tr cihazda Türkçe, En cihazda ise İngilizce oluyor eğer beni projenize katarsanız bu uygulamaya manuel dil değiştirme özelliği eklemek istiyorum.

**Comment by recepbasturk** [comment]
Merhaba
Tabi yapabilirsiniz dil değiştirme özelliği eklemenizi bekliyorum.
